############ Cluster noloop001.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches 765927b2d508712d320c8934db963bbe14c3fcec 0-7 noloop001.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop001.plfs....; sleep 9999999' &
############ Cluster noloop002.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches 3b8b487114c95ef6db5fef708ef69bfb5209014e 0-7 noloop002.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop002.plfs....; sleep 9999999' &
############ Cluster noloop003.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches 3c0a6163688b8ca3f44029c7bdb3d91a865c878a 0-7 noloop003.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop003.plfs....; sleep 9999999' &
############ Cluster noloop004.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches e8b96eb5034a0ccebf36760f88e31ea3e3cdf1e4 0-7 noloop004.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop004.plfs....; sleep 9999999' &
############ Cluster noloop005.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches a8c7176b6ded413d5044a00f1d05477b95a6d7ad 0-7 noloop005.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop005.plfs....; sleep 9999999' &
############ Cluster noloop006.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches a1177825719ccef3f76ef39bbfd5ebb6087d53c7 0-7 noloop006.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop006.plfs....; sleep 9999999' &
############ Cluster noloop007.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches 9e9ad5f408889db6038a59b38ede29ff1ba9ef2f 0-7 noloop007.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop007.plfs....; sleep 9999999' &
############ Cluster noloop008.plfs
screen bash -c 'python ~/workdir/exp-script/lazy-build-from-ops.py git nopatches 9d46be294d12871adf4206f89168b14d27adb8b5 0-7 noloop008.plfs notusefinished download,checkout,patch,make_oldconfig,make_kernel,tar_src,pull_src_tar,untar_src,install_kernel,set_default_kernel,reboot,wait_for_alive,never_writeback,check_current_version,clean,run_exp; echo sleeping for noloop008.plfs....; sleep 9999999' &

